function displayPoem(response) {
  let poemElement = document.querySelector("#generated-poem");

  poemElement.innerHTML = "";
  let poemText = response.data.answer;
  poemElement.innerHTML = poemText;

  new Typewriter(poemElement, {
    strings: response.data.answer,
    autoStart: true,
    delay: 40,
    cursor: "",
  });
}

function generatePoem(event) {
  event.preventDefault();

  let searchInput = document.querySelector("#search-input");
  let apiKey = "o1cfacc0a9aa5038bce80c403dc4abt1";
  let prompt = `User instructions: Write a poem based on ${searchInput.value}.`;
  let context =
    "You are a poem expert and love to write short, gentle poems with user instructions and separate each line with a <br />. Make sure to sign the poem at the bottom with 'Generated by AI SheCodes' inside a <strong> element.";
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  let poemContainerElement = document.querySelector("#generated-poem");
  poemContainerElement.classList.remove("hidden");

  poemContainerElement.innerHTML = `<div class="generating">⏳Generating a poem about ${searchInput.value}...</div>`;

  console.log(`Prompt: ${prompt}`);
  console.log(`Context: ${context}`);
  axios.get(apiUrl).then(displayPoem);
}

let poemFormElement = document.querySelector("#poem-form");
poemFormElement.addEventListener("submit", generatePoem);
